input:
  - path: test/resources/exapmle_height.zarr
    stacking_dim: "altitude"
  - path: test/resources/example_pressure.zarr
    stacking_dim: "pressure"

output:
  state: ["u", "v", "t", "r"]

coords: [x, y]
